name: Github Action Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello Wold"
    test-job:
      run-on: ubuntu-latest
      steps:
        - run: echo "sest job"
    deploy-job:
      run-on: ubuntu-latest
      steps:
        - run: echo "deploy"
