name: Github Action Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "build job"
    test-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "testjob"
    deploy-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "deploy job"
